# This is a basic workflow to help you get started with Actions

name: Deploy to Github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dotnet version to the ubuntu machine
      - name: Sets Up .Net Core SDK 6.0
        uses: actions/setup-dotnet@v1
        with: 
           dotnet-version: '6.0.x'
           include-prerelease: true

      # publish the dotnet blazor to the release folder
      - name: Publishes .NET core Project
        run: dotnet publish ./practice/practice.csproj -c Release -o release --nologo
        
      - name: Commit wwwroot to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
           branch: gh-pages
           folder: release/wwwroot
           
      - name: change base-tag in the index from '/' to '<nameofrepository>' to match github pages subdirectory
        run:  sed -i 's/<base href="\/" \/>/<base href="\/keyboards\/" \/>/g' release/wwwroot/index.html
        
        
       
